# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 192.168.56.10
  card: enp0s8
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1  
nodes:
  control:
    cpu: 2
    memory: 4096
    name: k8scp
  workers:
    count: 2
    cpu: 2
    memory: 4096
    name: k8swk
software:
  box: ubuntu/focal64
  cilium: 1.14.1
  kubernetes: 1.27.1-00
  os: xUbuntu_20.04
  